"use strict";
exports.HEROES = [
    { id: 3, name: 'Bill Terry', bio: 'Hit .341 during 14-year playing career with Giants...his .401 batting average in 1930 is highest in franchise history and marks last time NL player hit over .400...set Giants single-season records for hits (254) and runs scored (139) in 1930...became player/manager in 32 and posted 823-661 mark in 10 years as skipper...guided club to three pennants and one World Series...' },
    { id: 4, name: 'Mel Ott', bio: 'Played 22 years for Giants, including seven as player/manager...11-time All-Star is franchises all-time leader with 1,860 RBI...ranks behind only Willie Mays in games (2,730), at-bats (9,456), runs (1,859), hits (2,876), doubles (488), home runs (511), total bases (5,041) and extra base hits (1,071)...led team in homers every year from 1928-45...was 1st NL player to reach 500 HR...' },
    { id: 11, name: 'Carl Hubbell', bio: 'Nine-time All-Star posted 253-154 record in 16 seasons with Giants...his 1.66 ERA in 1933 is best in franchise history...posted franchise-record 46.1-consecutive scoreless innings in 1933...was NL MVP in 1933 and 36...won 24 straight decisions spanning 1936-37...struck out six batters in 1934 All-Star game at Polo Grounds, including Babe Ruth, Lou Gehrig and Jimmy Foxx...' },
    { id: 20, name: 'Monte Irvin', bio: "Played in the Negro leagues and also played with the Newark Eagles (1938-42, 46-48), New York Giants (1949-55) and Chicago Cubs (1956). He was one of the first African American players to be signed after baseball's color line was broken by Jackie Robinson in 1947. In 1951, Irvin sparked the Giants' miraculous comeback to overtake the Dodgers in the pennant race, batting .312 with 24 home runs and 121 RBI, en route to the World Series. That same year he teamed with Hank Thompson and Willie Mays to form the first all African American outfield in the Majors. In 1952 he was named to the NL All-Star team. Throughout his Major League career, Irvin batted .293 with 99 home runs, and 443 RBI in 764 games. He was inducted into the National Baseball Hall of Fame in 1973." },
    { id: 24, name: 'Willie Mays', bio: 'Lifetime .302 hitter with 660 career homers, third most in Major League history behind Hank Aaron and Babe Ruth...12-time Gold Glove winner appeared in 24 All-Star Games...was named NL MVP in 1954 and 65 and NL Rookie of Year in 51...is Giants all-time leader in games (2,857), at-bats (10,477), runs (2,011), hits (3,187), doubles (504), home runs (646), total bases (5,907) and extrabase hits (1,289)...named starting outfielder on MLBs All-Century Team...' },
    { id: 27, name: 'Juan Marichal', bio: 'Nine-time All-Star won 238 games in San Francisco, most by any pitcher since franchise moved west in 1958...won 20 or more games six times in 14 years with Giants...is SF leader in complete games (244), shutouts (52), innings (3,443) and strikeouts (2,281)...was named right-hander on Giants 60s and 70s All-Decade Teams and San Franciscos All-Time Team...' },
    { id: 30, name: 'Orlando Cepeda', bio: 'Was six-time All-Star during eight-plus years with Giants...earned NL Rookie of Year honors in 1958...holds SF season mark with 142 RBI in 1961...ranks among SF leaders in homers (5th - 226), RBI (3rd - 767), games (7th - 1,114), at-bats (6th - 4,178), runs (7th - 652), hits (3rd - 1,286) and doubles (5th - 226)...named to SFs All-Time team and Giants 1960s All-Decade Team...' },
    { id: 36, name: 'Gaylord Perry', bio: 'First pitcher in baseball history to win Cy Young Award in both American and National Leagues, fashioned 134-109 record with 2.96 ERA for Giants from 1962-71...ranks second in SF annals for wins, ERA, games started (283), complete games (125), shutouts (21), innings pitched (2,294.2) and strikeouts (1,606)...five-time 20-game winner and five-time All-Star is one of only four pitchers in SF history to win 100 games with club...24-year veteran is 16th all-time with 314 wins, and is one of seven pitchers ever to compile 300 wins and 3,500 strikeouts' },
    { id: 42, name: 'Jackie Robinson', bio: "Courageously broke Major League Baseball's color barrier with Brooklyn in 1947...five-time All-Star was named NL Rookie of Year in 1947 and MVP in '49...to commemorate 50th anniversary of his arrival in big leagues, number 42 was retired by every Major League team in 1997...was named to MLB's All-Century Team..." },
    { id: 44, name: 'Willie McCovey', bio: 'Six-time All-Star earned NL Rookie of Year honors in 1959 and MVP in 1969...leads all San Francisco players in games (2,256), home runs (469) and RBI (1555)...trails only Mays in at-bats (7,214), runs (1,113), hits (1,974), doubles (308) and triples (45)...holds NL record with 18 career grand slams...hit 231 career homers at Candlestick Park, more than any other player...' }
];
//# sourceMappingURL=mock-heroes.js.map